endpoints:
  actuator:
    enabled: true
  shutdown:
    enabled: false
fdfs:
  file-host: http://192.168.25.10:9999/
  tracker-list:
  - 192.168.25.10:22122
feign:
  client:
    config:
      feignName:
        connectTimeout: 30000
        readTimeout: 30000
  compression:
    request:
      enabled: true
    response:
      enabled: true
  httpclient:
    enabled: false
  hystrix:
    enabled: true
  okhttp:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
  threadpool:
    default:
      coreSize: 500
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 800
jasypt:
  encryptor:
    password: lengleng
management:
  security:
    enabled: false
mybatis-plus:
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
  global-config:
    db-column-underline: true
    field-strategy: 1
    id-type: 0
    refresh-mapper: true
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.github.pig.admin.model.entity
redis:
  cache:
    expiration: 3600
ribbon:
  ConnectTimeout: 10000
  Httpclient:
    enabled: false
  OkHttp:
    enabled: true
  ReadTimeout: 10000
  eager-load:
    clients: pig-auth,pig-upms-service
    enabled: true
server:
  port: 4002
  tomcat:
    max-threads: 500
    min-spare-threads: 50
sharding:
  jdbc:
    config:
      sharding:
        tables:
          sys_log:
            actual-data-nodes: ds.sys_log_${0..1}
            key-generator-column-name: id
            table-strategy:
              inline:
                algorithm-expression: sys_log_${id % 2}
                sharding-column: id
    datasource:
      ds:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/pig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
        password: 123456
        type: com.zaxxer.hikari.HikariDataSource
        username: root
      names: ds
    defaultDataSourceName:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/pig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      password: 123456
      type: com.zaxxer.hikari.HikariDataSource
      username: root
spring:
  http:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  rabbitmq:
    host: 127.0.0.1
    password: guest
    port: 5672
    username: guest
  redis:
    host: 127.0.0.1
    password: ''
    port: 6379
    remote: false
  sleuth:
    sampler:
      percentage: 0.2
  zipkin:
    rabbitmq:
      queue: zipkin